export const timetableKeys = {
  all: ["timetables"] as const,
  byYear: (academicYearId: string) => ["timetables", "by-year", academicYearId] as const,
  detail: (id: string) => ["timetables", "detail", id] as const,
  entries: (id: string) => ["timetables", "detail", id, "entries"] as const,
  validation: (id: string) => ["timetables", "detail", id, "validate"] as const,
  history: (id: string) => ["timetables", "detail", id, "history"] as const,
  publishedForClass: (classId: string, academicYearId: string) => ["timetables", "published", classId, academicYearId] as const,
  reviewQueue: (academicYearId: string) => ["timetables", "review-queue", academicYearId] as const,
  leadership: () => ["timetables", "leadership"] as const,
  myTeacherSchedule: (academicYearId: string) => ["timetables", "me", "teacher", academicYearId] as const,
  myClass: () => ["timetables", "me", "class"] as const,
  child: (studentId: string) => ["timetables", "child", studentId] as const,
  classrooms: () => ["timetables", "classrooms"] as const,
  gradeSections: (academicYearId: string) => ["timetables", "grade-sections", academicYearId] as const,
  gradeSectionPeriods: (id: string) => ["timetables", "grade-sections", "detail", id, "periods"] as const,
  subjectRequirements: (academicYearId: string, gradeId: string) => ["timetables", "subject-requirements", academicYearId, gradeId] as const,
  settings: (academicYearId: string) => ["timetables", "settings", academicYearId] as const,
};
