// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_erasures.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deletePendingErasure = `-- name: DeletePendingErasure :exec
DELETE FROM pending_identity_erasures WHERE id = $1
`

func (q *Queries) DeletePendingErasure(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePendingErasure, id)
	return err
}

const listPendingErasures = `-- name: ListPendingErasures :many
SELECT id, user_id, local_done, idp_done, last_error, attempts, created_at, updated_at FROM pending_identity_erasures
WHERE NOT (local_done AND idp_done)
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingErasures(ctx context.Context, limit int32) ([]PendingIdentityErasure, error) {
	rows, err := q.db.Query(ctx, listPendingErasures, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingIdentityErasure{}
	for rows.Next() {
		var i PendingIdentityErasure
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LocalDone,
			&i.IdpDone,
			&i.LastError,
			&i.Attempts,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPendingErasure = `-- name: UpsertPendingErasure :exec
INSERT INTO pending_identity_erasures (user_id, local_done, idp_done, last_error, attempts)
VALUES ($1, $2, $3, $4, 1)
ON CONFLICT (user_id) DO UPDATE SET
    local_done = pending_identity_erasures.local_done OR EXCLUDED.local_done,
    idp_done   = pending_identity_erasures.idp_done OR EXCLUDED.idp_done,
    last_error = EXCLUDED.last_error,
    attempts   = pending_identity_erasures.attempts + 1,
    updated_at = now()
`

type UpsertPendingErasureParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	LocalDone bool        `json:"local_done"`
	IdpDone   bool        `json:"idp_done"`
	LastError pgtype.Text `json:"last_error"`
}

// Records that a user still needs identity cleanup after its profile was
// already anonymised. local_done/idp_done only ever move true → stays true
// (the OR keeps a step already confirmed done from being un-done by a
// retry that only re-attempts the other step).
func (q *Queries) UpsertPendingErasure(ctx context.Context, arg UpsertPendingErasureParams) error {
	_, err := q.db.Exec(ctx, upsertPendingErasure,
		arg.UserID,
		arg.LocalDone,
		arg.IdpDone,
		arg.LastError,
	)
	return err
}
