// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: students.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const anonymizeStudentProfile = `-- name: AnonymizeStudentProfile :exec
UPDATE student_profiles
SET
    full_name       = 'Erased Student',
    address         = NULL,
    phone           = NULL,
    whatsapp        = NULL,
    special_remarks = NULL,
    gender          = NULL,
    erased_at       = NOW(),
    updated_at      = NOW()
WHERE id = $1
`

func (q *Queries) AnonymizeStudentProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, anonymizeStudentProfile, id)
	return err
}

const createStudentProfile = `-- name: CreateStudentProfile :one
INSERT INTO student_profiles (
    user_id,
    full_name,
    index_number,
    address,
    phone,
    whatsapp,
    special_remarks,
    gender,
    house_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, user_id, full_name, index_number, address, phone, whatsapp, special_remarks, created_at, updated_at, gender, house_id, enrollment_status
`

type CreateStudentProfileParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	FullName       string      `json:"full_name"`
	IndexNumber    string      `json:"index_number"`
	Address        pgtype.Text `json:"address"`
	Phone          pgtype.Text `json:"phone"`
	Whatsapp       pgtype.Text `json:"whatsapp"`
	SpecialRemarks pgtype.Text `json:"special_remarks"`
	Gender         pgtype.Text `json:"gender"`
	HouseID        pgtype.UUID `json:"house_id"`
}

func (q *Queries) CreateStudentProfile(ctx context.Context, arg CreateStudentProfileParams) (StudentProfile, error) {
	row := q.db.QueryRow(ctx, createStudentProfile,
		arg.UserID,
		arg.FullName,
		arg.IndexNumber,
		arg.Address,
		arg.Phone,
		arg.Whatsapp,
		arg.SpecialRemarks,
		arg.Gender,
		arg.HouseID,
	)
	var i StudentProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.IndexNumber,
		&i.Address,
		&i.Phone,
		&i.Whatsapp,
		&i.SpecialRemarks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Gender,
		&i.HouseID,
		&i.EnrollmentStatus,
	)
	return i, err
}

const deleteStudentProfile = `-- name: DeleteStudentProfile :exec
DELETE FROM student_profiles
WHERE id = $1
`

func (q *Queries) DeleteStudentProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStudentProfile, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT id, user_id, full_name, index_number, address, phone, whatsapp, special_remarks, created_at, updated_at, gender, house_id, enrollment_status FROM student_profiles
WHERE id = $1
`

func (q *Queries) GetStudentByID(ctx context.Context, id uuid.UUID) (StudentProfile, error) {
	row := q.db.QueryRow(ctx, getStudentByID, id)
	var i StudentProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.IndexNumber,
		&i.Address,
		&i.Phone,
		&i.Whatsapp,
		&i.SpecialRemarks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Gender,
		&i.HouseID,
		&i.EnrollmentStatus,
	)
	return i, err
}

const getStudentByIndexNumber = `-- name: GetStudentByIndexNumber :one
SELECT id, user_id, full_name, index_number, address, phone, whatsapp, special_remarks, created_at, updated_at, gender, house_id, enrollment_status FROM student_profiles
WHERE index_number = $1
`

func (q *Queries) GetStudentByIndexNumber(ctx context.Context, indexNumber string) (StudentProfile, error) {
	row := q.db.QueryRow(ctx, getStudentByIndexNumber, indexNumber)
	var i StudentProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.IndexNumber,
		&i.Address,
		&i.Phone,
		&i.Whatsapp,
		&i.SpecialRemarks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Gender,
		&i.HouseID,
		&i.EnrollmentStatus,
	)
	return i, err
}

const getStudentByUserID = `-- name: GetStudentByUserID :one
SELECT id, user_id, full_name, index_number, address, phone, whatsapp, special_remarks, created_at, updated_at, gender, house_id, enrollment_status FROM student_profiles
WHERE user_id = $1
`

func (q *Queries) GetStudentByUserID(ctx context.Context, userID pgtype.UUID) (StudentProfile, error) {
	row := q.db.QueryRow(ctx, getStudentByUserID, userID)
	var i StudentProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.IndexNumber,
		&i.Address,
		&i.Phone,
		&i.Whatsapp,
		&i.SpecialRemarks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Gender,
		&i.HouseID,
		&i.EnrollmentStatus,
	)
	return i, err
}

const getStudentWithClass = `-- name: GetStudentWithClass :one
SELECT
    sp.id, sp.user_id, sp.full_name, sp.index_number, sp.address, sp.phone, sp.whatsapp, sp.special_remarks, sp.created_at, sp.updated_at, sp.gender, sp.house_id, sp.enrollment_status,
    u.email       AS email,
    c.name        AS class_name,
    g.name        AS grade_name,
    h.name        AS house_name,
    ay.label      AS academic_year
FROM student_profiles sp
LEFT JOIN users u            ON u.id = sp.user_id
LEFT JOIN class_students cs ON cs.student_id = sp.id
LEFT JOIN classes c         ON c.id = cs.class_id
LEFT JOIN grades g          ON g.id = c.grade_id
LEFT JOIN houses h          ON h.id = sp.house_id
LEFT JOIN academic_years ay ON ay.id = c.academic_year_id AND ay.is_current = TRUE
WHERE sp.id = $1
`

type GetStudentWithClassRow struct {
	ID               uuid.UUID          `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	FullName         string             `json:"full_name"`
	IndexNumber      string             `json:"index_number"`
	Address          pgtype.Text        `json:"address"`
	Phone            pgtype.Text        `json:"phone"`
	Whatsapp         pgtype.Text        `json:"whatsapp"`
	SpecialRemarks   pgtype.Text        `json:"special_remarks"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Gender           pgtype.Text        `json:"gender"`
	HouseID          pgtype.UUID        `json:"house_id"`
	EnrollmentStatus string             `json:"enrollment_status"`
	Email            pgtype.Text        `json:"email"`
	ClassName        pgtype.Text        `json:"class_name"`
	GradeName        pgtype.Text        `json:"grade_name"`
	HouseName        pgtype.Text        `json:"house_name"`
	AcademicYear     pgtype.Text        `json:"academic_year"`
}

func (q *Queries) GetStudentWithClass(ctx context.Context, id uuid.UUID) (GetStudentWithClassRow, error) {
	row := q.db.QueryRow(ctx, getStudentWithClass, id)
	var i GetStudentWithClassRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.IndexNumber,
		&i.Address,
		&i.Phone,
		&i.Whatsapp,
		&i.SpecialRemarks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Gender,
		&i.HouseID,
		&i.EnrollmentStatus,
		&i.Email,
		&i.ClassName,
		&i.GradeName,
		&i.HouseName,
		&i.AcademicYear,
	)
	return i, err
}

const listStudents = `-- name: ListStudents :many
SELECT
    sp.id, sp.user_id, sp.full_name, sp.index_number, sp.address, sp.phone, sp.whatsapp, sp.special_remarks, sp.created_at, sp.updated_at, sp.gender, sp.house_id, sp.enrollment_status,
    c.name AS class_name,
    g.name AS grade_name,
    h.name AS house_name
FROM student_profiles sp
LEFT JOIN class_students cs
    ON cs.student_id = sp.id
   AND cs.academic_year_id = (
       SELECT id FROM academic_years WHERE is_current = TRUE LIMIT 1
   )
LEFT JOIN classes c ON c.id = cs.class_id
LEFT JOIN grades  g ON g.id = c.grade_id
LEFT JOIN houses  h ON h.id = sp.house_id
ORDER BY sp.full_name ASC
`

type ListStudentsRow struct {
	ID               uuid.UUID          `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	FullName         string             `json:"full_name"`
	IndexNumber      string             `json:"index_number"`
	Address          pgtype.Text        `json:"address"`
	Phone            pgtype.Text        `json:"phone"`
	Whatsapp         pgtype.Text        `json:"whatsapp"`
	SpecialRemarks   pgtype.Text        `json:"special_remarks"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Gender           pgtype.Text        `json:"gender"`
	HouseID          pgtype.UUID        `json:"house_id"`
	EnrollmentStatus string             `json:"enrollment_status"`
	ClassName        pgtype.Text        `json:"class_name"`
	GradeName        pgtype.Text        `json:"grade_name"`
	HouseName        pgtype.Text        `json:"house_name"`
}

func (q *Queries) ListStudents(ctx context.Context) ([]ListStudentsRow, error) {
	rows, err := q.db.Query(ctx, listStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentsRow{}
	for rows.Next() {
		var i ListStudentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FullName,
			&i.IndexNumber,
			&i.Address,
			&i.Phone,
			&i.Whatsapp,
			&i.SpecialRemarks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Gender,
			&i.HouseID,
			&i.EnrollmentStatus,
			&i.ClassName,
			&i.GradeName,
			&i.HouseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsPage = `-- name: ListStudentsPage :many
SELECT
    sp.id, sp.user_id, sp.full_name, sp.index_number, sp.address, sp.phone, sp.whatsapp, sp.special_remarks, sp.created_at, sp.updated_at, sp.gender, sp.house_id, sp.enrollment_status,
    c.name AS class_name,
    g.name AS grade_name,
    h.name AS house_name,
    COUNT(*) OVER () AS total
FROM student_profiles sp
LEFT JOIN class_students cs
    ON cs.student_id = sp.id
   AND cs.academic_year_id = (
       SELECT id FROM academic_years WHERE is_current = TRUE LIMIT 1
   )
LEFT JOIN classes c ON c.id = cs.class_id
LEFT JOIN grades  g ON g.id = c.grade_id
LEFT JOIN houses  h ON h.id = sp.house_id
WHERE ($1::text IS NULL OR sp.full_name ILIKE '%' || $1::text || '%' OR sp.index_number ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL OR g.name = $2::text)
  AND ($3::text IS NULL OR c.name = $3::text)
  AND ($4::text IS NULL OR sp.gender = $4::text)
  AND ($5::text IS NULL OR h.name = $5::text)
ORDER BY sp.full_name ASC, sp.id ASC
LIMIT $6::int OFFSET $7::int
`

type ListStudentsPageParams struct {
	Search     pgtype.Text `json:"search"`
	Grade      pgtype.Text `json:"grade"`
	Class      pgtype.Text `json:"class"`
	Gender     pgtype.Text `json:"gender"`
	House      pgtype.Text `json:"house"`
	PageLimit  int32       `json:"page_limit"`
	PageOffset int32       `json:"page_offset"`
}

type ListStudentsPageRow struct {
	ID               uuid.UUID          `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	FullName         string             `json:"full_name"`
	IndexNumber      string             `json:"index_number"`
	Address          pgtype.Text        `json:"address"`
	Phone            pgtype.Text        `json:"phone"`
	Whatsapp         pgtype.Text        `json:"whatsapp"`
	SpecialRemarks   pgtype.Text        `json:"special_remarks"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Gender           pgtype.Text        `json:"gender"`
	HouseID          pgtype.UUID        `json:"house_id"`
	EnrollmentStatus string             `json:"enrollment_status"`
	ClassName        pgtype.Text        `json:"class_name"`
	GradeName        pgtype.Text        `json:"grade_name"`
	HouseName        pgtype.Text        `json:"house_name"`
	// Hand-edited: excluded from JSON since the handler reads it once for the
	// page envelope's top-level "total" rather than repeating it per row.
	Total int64 `json:"-"`
}

func (q *Queries) ListStudentsPage(ctx context.Context, arg ListStudentsPageParams) ([]ListStudentsPageRow, error) {
	rows, err := q.db.Query(ctx, listStudentsPage,
		arg.Search,
		arg.Grade,
		arg.Class,
		arg.Gender,
		arg.House,
		arg.PageLimit,
		arg.PageOffset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentsPageRow{}
	for rows.Next() {
		var i ListStudentsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FullName,
			&i.IndexNumber,
			&i.Address,
			&i.Phone,
			&i.Whatsapp,
			&i.SpecialRemarks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Gender,
			&i.HouseID,
			&i.EnrollmentStatus,
			&i.ClassName,
			&i.GradeName,
			&i.HouseName,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsByClass = `-- name: ListStudentsByClass :many
SELECT
    sp.id, sp.user_id, sp.full_name, sp.index_number, sp.address, sp.phone, sp.whatsapp, sp.special_remarks, sp.created_at, sp.updated_at, sp.gender, sp.house_id, sp.enrollment_status
FROM student_profiles sp
INNER JOIN class_students cs ON cs.student_id = sp.id
WHERE cs.class_id = $1
ORDER BY sp.full_name ASC
`

func (q *Queries) ListStudentsByClass(ctx context.Context, classID uuid.UUID) ([]StudentProfile, error) {
	rows, err := q.db.Query(ctx, listStudentsByClass, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudentProfile{}
	for rows.Next() {
		var i StudentProfile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FullName,
			&i.IndexNumber,
			&i.Address,
			&i.Phone,
			&i.Whatsapp,
			&i.SpecialRemarks,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Gender,
			&i.HouseID,
			&i.EnrollmentStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudentEnrollmentStatus = `-- name: UpdateStudentEnrollmentStatus :one
UPDATE student_profiles
SET
    enrollment_status = $2,
    left_at           = CASE WHEN $2 = 'left' THEN NOW() ELSE NULL END,
    updated_at        = NOW()
WHERE id = $1
RETURNING id, user_id, full_name, index_number, address, phone, whatsapp, special_remarks, created_at, updated_at, gender, house_id, enrollment_status
`

type UpdateStudentEnrollmentStatusParams struct {
	ID               uuid.UUID `json:"id"`
	EnrollmentStatus string    `json:"enrollment_status"`
}

func (q *Queries) UpdateStudentEnrollmentStatus(ctx context.Context, arg UpdateStudentEnrollmentStatusParams) (StudentProfile, error) {
	row := q.db.QueryRow(ctx, updateStudentEnrollmentStatus, arg.ID, arg.EnrollmentStatus)
	var i StudentProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.IndexNumber,
		&i.Address,
		&i.Phone,
		&i.Whatsapp,
		&i.SpecialRemarks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Gender,
		&i.HouseID,
		&i.EnrollmentStatus,
	)
	return i, err
}

const updateStudentProfile = `-- name: UpdateStudentProfile :one
UPDATE student_profiles
SET
    full_name       = $2,
    address         = $3,
    phone           = $4,
    whatsapp        = $5,
    special_remarks = $6,
    gender          = $7,
    updated_at      = NOW()
WHERE id = $1
RETURNING id, user_id, full_name, index_number, address, phone, whatsapp, special_remarks, created_at, updated_at, gender, house_id, enrollment_status
`

type UpdateStudentProfileParams struct {
	ID             uuid.UUID   `json:"id"`
	FullName       string      `json:"full_name"`
	Address        pgtype.Text `json:"address"`
	Phone          pgtype.Text `json:"phone"`
	Whatsapp       pgtype.Text `json:"whatsapp"`
	SpecialRemarks pgtype.Text `json:"special_remarks"`
	Gender         pgtype.Text `json:"gender"`
}

func (q *Queries) UpdateStudentProfile(ctx context.Context, arg UpdateStudentProfileParams) (StudentProfile, error) {
	row := q.db.QueryRow(ctx, updateStudentProfile,
		arg.ID,
		arg.FullName,
		arg.Address,
		arg.Phone,
		arg.Whatsapp,
		arg.SpecialRemarks,
		arg.Gender,
	)
	var i StudentProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.IndexNumber,
		&i.Address,
		&i.Phone,
		&i.Whatsapp,
		&i.SpecialRemarks,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Gender,
		&i.HouseID,
		&i.EnrollmentStatus,
	)
	return i, err
}

const listStudentsPastRetention = `-- name: ListStudentsPastRetention :many
SELECT id, user_id, full_name, left_at
FROM student_profiles
WHERE enrollment_status = 'left'
  AND erased_at IS NULL
  AND left_at IS NOT NULL
  AND left_at < NOW() - make_interval(years => $1::int)
ORDER BY left_at
`

type ListStudentsPastRetentionRow struct {
	ID       uuid.UUID          `json:"id"`
	UserID   pgtype.UUID        `json:"user_id"`
	FullName string             `json:"full_name"`
	LeftAt   pgtype.Timestamptz `json:"left_at"`
}

func (q *Queries) ListStudentsPastRetention(ctx context.Context, retentionYears int32) ([]ListStudentsPastRetentionRow, error) {
	rows, err := q.db.Query(ctx, listStudentsPastRetention, retentionYears)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentsPastRetentionRow{}
	for rows.Next() {
		var i ListStudentsPastRetentionRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.FullName, &i.LeftAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
